# Generated by Django 4.1.5 on 2023-01-18 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0003_alter_customuser_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
