# Generated by Django 4.1.5 on 2023-01-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0004_alter_customuser_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=20),
        ),
    ]
