# Generated by Django 4.1.5 on 2023-01-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0006_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="chat_id",
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_connected",
            field=models.BooleanField(default=False),
        ),
    ]
